name: fexmonths
description: A Store for Insallment

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  animated_drawer: ^0.0.4
  googleapis_auth: ^1.3.1
  flutter_screenutil: ^5.6.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  rflutter_alert: ^2.0.4
  http: ^0.13.5
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  dio: ^5.0.2
  provider:
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+7
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  geolocator: ^9.0.2
  modal_bottom_sheet: ^2.1.2
  syncfusion_flutter_gauges: ^18.2.44
  logger:
  cached_network_image:
  loading_overlay_pro:
  intl:





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
flutter:
  uses-material-design: true
  assets:
    - Images/
    - assets/locations.json

